# testlists user
testlists_user: testlists
testlists_home: "/opt/{{ testlists_user }}"

# testlists settings
clickhouse_url: "clickhouse://write:{{ lookup('amazon.aws.aws_ssm', '/oonidevops/secrets/clickhouse_write_password', profile='oonidevops_user_prod') }}@clickhouseproxy.dev.ooni.io/oonitest"
