---
groups:
- name: OONI Alerts
  rules:
  - alert: NASBackupSilent
    expr: time() - push_time_seconds{exported_instance="hellais-nas"} > 48 * 3600
    annotations:
      summary: 'hellais-nas is silent for {{ $value | humanizeDuration }}'

  - alert: NASRsyncFailure
    expr: rsync_returncode{exported_instance="hellais-nas"} != 0
    for: 48h # rsync is launched at 08:00 and 22:00, that's 14h and 10h gap
    annotations:
      summary: 'hellais-nas `rsync` exitcode: {{ $value }}'

  # Some nodes may have it broken, but it usually works, here is expr to validate it.
  # expr: (max without (device) (node_seeksample_timestamp{job="node"}) or up{job="node"}) == 1
  - alert: DiskStuck
    expr: node_time - ignoring(device) group_right node_seeksample_timestamp > 240
    annotations:
      summary: '{{ $labels.instance }} has `{{ $labels.device }}` silent for {{ $value | humanizeDuration }}'

...
