- name: reload nftables
  tags: nftables
  ansible.builtin.systemd_service:
    name: nftables
    state: reloaded

- name: restart docker
  tags: docker
  ansible.builtin.systemd_service:
    name: docker
    state: restarted
