---
- name: Check current node_exporter version.
  command: "{{ node_exporter_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: node_exporter_version_check

- name: Download and unarchive node_exporter into temporary location.
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /tmp
    remote_src: true
    mode: 0755
  when: >
    node_exporter_version_check.stdout is not defined
    or node_exporter_version not in node_exporter_version_check.stdout
  register: node_exporter_download_check

- name: Move node_exporter binary into place.
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}/node_exporter"
    dest: "{{ node_exporter_bin_path }}"
    mode: 0755
    remote_src: true
  notify: restart node_exporter
  when: >
    node_exporter_download_check is changed
    or node_exporter_version_check.stdout | length == 0

- name: Create node_exporter group.
  group:
    name: "{{ prometheus_group }}"
    state: present

- name: Create node_exporter user.
  user:
    name: "{{ prometheus_user }}"
    shell: /sbin/nologin
    group: "{{ prometheus_group }}"
    state: present

- name: Add a user to a password file and ensure permissions are set
  community.general.htpasswd:
    path: "{{ node_exporter_htpasswd }}"
    name: prom
    password: "{{ prometheus_metrics_password }}"
    owner: root
    group: "{{ 'nginx' if use_nginx else prometheus_group }}"
    mode: 0640
  tags:
    - monitoring
    - node_exporter
    - config
  when: use_nginx

- name: Copy ooni CA cert for client authentication
  copy:
    src: scraper_ca.cert
    dest: /etc/ssl/certs/scraper_ca.cert
    mode: 0644
    owner: root
    group: root

- name: Copy node_exporter web_config
  template:
    src: node_exporter_web_config.j2
    dest: /etc/ooni/node_exporter_web_config.yml
    mode: 0644

- name: Copy the node_exporter systemd unit file.
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644
  register: node_exporter_service

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart node_exporter
  when: node_exporter_service is changed

- name: Ensure node_exporter is running and enabled at boot.
  service:
    name: node_exporter
    state: "{{ node_exporter_state }}"
    enabled: "{{ node_exporter_enabled }}"

- name: Verify node_exporter is responding to requests.
  uri:
    url: "http://{% if node_exporter_host !='' %}{{ node_exporter_host }}{% else %}localhost{% endif %}:{{ node_exporter_port }}/"
    return_content: true
  register: metrics_output
  failed_when: "'Metrics' not in metrics_output.content"
